spring:
  application:
    name: API-Gateway
  cloud:
    gateway:
      routes:
      - id: CUSTOMER
        uri: lb://CUSTOMER
        predicates:
        - Path=/customer/**
      - id: ORDER
        uri: lb://ORDER
        predicates:
        - Path=/order/**
      - id: RESTAURANT
        uri: lb://RESTAURANT
        predicates:
        - Path=/restaurant/**
      - id: DELIVERY
        uri: lb://DELIVERY
        predicates:
        - Path=/delivery/**
server:
  port: 8082
