server:
  port: 7072
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Chinna@1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  application:
    name: ORDER