server:
  port: 7071
spring:
  application:
    name: CUSTOMER	
  datasource:
    url: jdbc:mysql://localhost:3306/customer_db
    username: root
    password: Chinna@1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
